version: "3.5"

services:
  island:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_UPGRADE_TOOLS: "* 3 * * Mon"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 1
      SERVERMAP: "TheIsland"
      SESSION_NAME: "ARK Cluster TheIsland"
      MAX_PLAYERS: 15
      RCON_ENABLE: "True"
      RCON_PORT: 32330
      GAME_PORT: 7778
      QUERY_PORT: 27015
      RAW_SOCKETS: "False"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "keepmesecret"
      SPECTATOR_PASSWORD: "keepmesecret"
      MODS: "731604991"
      CLUSTER_ID: "keepmesecret"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - server_island:/ark
      - cluster:/cluster
    ports:
      - "32330:32330/tcp"
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27015:27015/udp"

  valguero:
    image: r15ch13/arkcluster:latest
    deploy:
      mode: global
    environment:
      CRON_UPGRADE_TOOLS: "* 3 * * Mon"
      UPDATEONSTART: 1
      BACKUPONSTART: 1
      BACKUPONSTOP: 1
      WARNONSTOP: 1
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: "UTC"
      MAX_BACKUP_SIZE: 1
      SERVERMAP: "Valguero_P"
      SESSION_NAME: "ARK Cluster Valguero"
      MAX_PLAYERS: 15
      RCON_ENABLE: "True"
      RCON_PORT: 32331
      GAME_PORT: 7780
      QUERY_PORT: 27016
      RAW_SOCKETS: "False"
      SERVER_PASSWORD: ""
      ADMIN_PASSWORD: "keepmesecret"
      SPECTATOR_PASSWORD: "keepmesecret"
      MODS: "731604991"
      CLUSTER_ID: "keepmesecret"
      KILL_PROCESS_TIMEOUT: 300
      KILL_ALL_PROCESSES_TIMEOUT: 300
    volumes:
      - server_valguero:/ark
      - cluster:/cluster
    ports:
      - "32331:32331/tcp"
      - "7779:7779/udp"
      - "7780:7780/udp"
      - "27016:27016/udp"

volumes:
  server_island:
  server_valguero:
  cluster:
